dict_value {
  fields {
    key: "collect_data_spec"
    value {
      named_tuple_value {
        name: "Trajectory"
        values {
          key: "step_type"
          value {
            tensor_spec_value {
              name: "step_type"
              shape {
              }
              dtype: DT_INT32
            }
          }
        }
        values {
          key: "observation"
          value {
            bounded_tensor_spec_value {
              name: "observation"
              shape {
                dim {
                  size: 28
                }
              }
              dtype: DT_FLOAT
              minimum {
                dtype: DT_FLOAT
                tensor_shape {
                  dim {
                    size: 28
                  }
                }
                tensor_content: "\262\263I\300\262\263I\300\262\263I\300\262\263I\300\262\263I\300\262\263I\300\262\263I\300\262\263I\300\222\271\'\303\222\271\'\303\222\271\'\303\222\271\'\303\222\271\'\303\222\271\'\303\222\271\'\303\222\271\'\303R\270\266\300R\270\266\300R\270\266\300R\270\266\300R\270\266\300R\270\266\300R\270\266\300R\270\266\300\256G\201\277\256G\201\277\256G\201\277\256G\201\277"
              }
              maximum {
                dtype: DT_FLOAT
                tensor_shape {
                  dim {
                    size: 28
                  }
                }
                tensor_content: "\262\263I@\262\263I@\262\263I@\262\263I@\262\263I@\262\263I@\262\263I@\262\263I@\222\271\'C\222\271\'C\222\271\'C\222\271\'C\222\271\'C\222\271\'C\222\271\'C\222\271\'CR\270\266@R\270\266@R\270\266@R\270\266@R\270\266@R\270\266@R\270\266@R\270\266@\256G\201?\256G\201?\256G\201?\256G\201?"
              }
            }
          }
        }
        values {
          key: "action"
          value {
            bounded_tensor_spec_value {
              name: "action"
              shape {
                dim {
                  size: 8
                }
              }
              dtype: DT_FLOAT
              minimum {
                dtype: DT_FLOAT
                tensor_shape {
                }
                float_val: -1.0
              }
              maximum {
                dtype: DT_FLOAT
                tensor_shape {
                }
                float_val: 1.0
              }
            }
          }
        }
        values {
          key: "policy_info"
          value {
            tuple_value {
            }
          }
        }
        values {
          key: "next_step_type"
          value {
            tensor_spec_value {
              name: "step_type"
              shape {
              }
              dtype: DT_INT32
            }
          }
        }
        values {
          key: "reward"
          value {
            tensor_spec_value {
              name: "reward"
              shape {
              }
              dtype: DT_FLOAT
            }
          }
        }
        values {
          key: "discount"
          value {
            bounded_tensor_spec_value {
              name: "discount"
              shape {
              }
              dtype: DT_FLOAT
              minimum {
                dtype: DT_FLOAT
                tensor_shape {
                }
                float_val: 0.0
              }
              maximum {
                dtype: DT_FLOAT
                tensor_shape {
                }
                float_val: 1.0
              }
            }
          }
        }
      }
    }
  }
  fields {
    key: "policy_state_spec"
    value {
      tuple_value {
      }
    }
  }
}
